/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GeoFrameBuilderForSmallBasin;





import static org.junit.Assert.assertTrue;

import org.geoframe.blogpost.zoom.Library;
import org.junit.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod());
    }
}
